spring.application.name=ExpenseFlow

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-calm-bread-b5mh0395-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IcN2gjU8aCzY
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=ExpenseTrackerSecretKeyForJWTTokenGenerationAndValidation2026
jwt.expiration=86400000



